### ISSUE TITLE
[Automation - BUG] PowerBI fails to load

### ISSUE THREAD

**Issue by nbetters** [microsoft/powercat-automation-kit#126] opened 2023-01-04 20:51 UTC
### Describe the issue

Power BI Fails to load
org URL is correct, I have tried with the Https (which causes a power bi issue) and without
![image](https://user-images.githubusercontent.com/55587135/210647006-18242eb4-4d13-4bae-9046-17f683a60282.png)
![image](https://user-images.githubusercontent.com/55587135/210647205-274a7cbd-18f7-4f29-8690-7cb016f241ba.png)

### Expected Behavior

Power bi report should open with reference to the data tables.

### What component are you experiencing the issue with?

Power BI dashboard

### What solution version are you using?

Automation.Kit.V1.0.20220914

### What app or flow are you having the issue with?

Power BI

### Steps To Reproduce

1. Download recent power Bi from github files
2.  Open
3. add main environment url
4. fails to open

### Anything else?

I should note, that this Power BI was working, but it was intermittent at best, certain cards would fail and I would need to continually re open the report to get them to load.

**Comment by KoteshMCGit** [comment] 2023-01-05 07:17
As per your screen shot, some network connectivity issue happens and could not able to connect to main environment. just now I have tried and could not able to reproduce the issue.

Suggestion:
Can you please download powerbi file once again from github and try to connect without https.

**Comment by nbetters** [comment] 2023-01-05 14:08
I re downloaded the file and tried, still failed. I don't have connectivity issues with anything else, all my systems are working fine including VM connections etc.

**Comment by nbetters** [comment] 2023-01-05 15:34
THere are errors in the mappings, we have Not edited these. This is a new file downloaded from git.
![image](https://user-images.githubusercontent.com/55587135/210819173-df085899-186a-40bc-8f10-b8f4891b544d.png)

**Comment by KoteshMCGit** [comment] 2023-01-06 12:18
Regarding Hours Saved column: It is calculated based on below columns. I am thinking that data is not provided for table Automation project records and field "Total Processing Time in Minutes"

Could you please verify the data in field "Total Processing Time in Minutes" of Autocoe_AutomationProjects table in main environment. Please correct the data and try to connect once again.

Regarding completed on date field value Error:
As per our Analysis and above screenshot (Error on completed on date column) , it is a data issue (empty values or wrong format of data found) in field of completed on of table autocoe_flowsessiontrace in main environment. if you observe empty values in this field, pls let us know for further investigation.

**Comment by nbetters** [comment] 2023-01-06 14:30
Regarding the date field value, I fixed the power bi by changing the date format to "Short Date" in the syntax. I Checked the table and there are no flow traces missing completed on, started, or created dates

**Comment by nbetters** [comment] 2023-01-06 14:47
In regards to total saved hours:

Flow session traces has a total process duration column, all our entries have data, however, some of them are 0 minutes, we have robots that literally take 30 seconds to complete that run every 10 minutes so there's thousands of entries that are only seconds long, we do not want to loose the aggregate value of these. I think that's whats causing the negative?

From: Nathan Betters
Sent: Friday, January 6, 2023 8:31 AM
To: microsoft/powercat-automation-kit ***@***.***>; microsoft/powercat-automation-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/powercat-automation-kit] [Automation - BUG] PowerBI fails to load (Issue #126)

Regarding the date field value, I fixed the power bi by changing the date format to "Short Date" in the syntax. I Checked the table and there are no flow traces missing completed on, started, or created dates

**Comment by nbetters** [comment] 2023-01-09 14:13
Also, if the flow session is pending it would make sense that the total process time not be calculated yet, which appears to break the power bi because that field is empty

**Comment by KoteshMCGit** [comment] 2023-01-19 15:20
we could not able to re-produce the pending flow session scenario. Please share the exact re-produce steps for further investigation.

**Comment by nbetters** [comment] 2023-01-19 15:32
Oddly this has not been an issue for the last week, it loads every time...

**Comment by KoteshMCGit** [comment] 2023-01-31 10:10
It is a data issue. after fixing the data , now Dashboard is loading properly and closing the issue.

**Closed by KoteshMCGit** 2023-01-31 10:10 UTC
Labels: bug

**Comment by KoteshMCGit** [comment] 2023-02-06 06:13
As per our analysis, we could not be able to re-produce the pending type of transactions. we have tried with different process duration bots like 30 mins, 1 hour and 2 hours duration bots. After completing of process, immediately flow session is created in respective table.

To Fix the issue:
1. Updating of completed Date column- We can fix it with using of start date in case completed date is blank or null or empty space.
2. For pending status records- As per default PB Dashboard Design, these records will be considered as failed. For failed records- Total savings column will be calculated as negative as below.

Total Savings= Cost Overhead + Cost to Remediate Per Instance

Below of Process time related fields will be Empty space as Start and completed dates are same, so no process duration.
Process Time (seconds) = Empty space
Process Time (mins) = Empty space
Process Time (Hours) = Empty space

if you feel different ROI calculation for pending status records, please let me know with example data. we will do further analysis and try to work on.

**Comment by nbetters** [comment] 2023-02-06 15:20
Pending records should not be "failed" transactions, if anything they should be omitted in BI calculations.

However, we have successful runs calculating negative savings, these are runs that have start and finish dates in them.

https://www.screencast.com/t/pR4zNmIpV

This would probably be better explored on a screenshare?

**Comment by nbetters** [comment] 2023-02-06 15:22
I should note, the completed on date is not populating in the BI report for these successful runs either..

**Comment by KoteshMCGit** [comment] 2023-02-07 12:17
Based on your video, i have found the below observations in your data.

![image](https://user-images.githubusercontent.com/107620140/217240114-863811ff-050e-4998-8d53-2565b937bbbf.png)

Observatoin1: As per your above screen shot overall status is ="Successful" but as per design of automation kit is ="Succeeded"- it is causing the issue. I am thinking that you might change the overall status from pending to "Successful". it is causing the issue like Total saving is going to negative.

Observatoin2: And also observed Time Completed column in flow session table is having formula error. 
screen shot of your video.
![image](https://user-images.githubusercontent.com/107620140/217241322-31525f0b-850d-4606-89df-6332019a5548.png)

Please correct the observation1 and verify once. if you have still needed any clarification regarding ROI, we can connect once in Teams (kmarram@microsoft.com).

**Comment by mikefactorial** [comment] 2023-02-15 17:54
@nbetters This has been fixed in the latest release.
